# Generated by Django 6.0.4 on 2026-04-22 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
        ('pharmacies', '0003_pharmacy_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='pharmacies.pharmacy'),
        ),
    ]
