# Generated by Django 5.2 on 2026-04-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0002_pharmacy_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='pharmacy_logos/'),
        ),
    ]
